-- 创建核酸检测结果表
CREATE TABLE nucleic_acid_results (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,              -- 姓名
  id_number VARCHAR(18) NOT NULL,          -- 身份证号
  phone VARCHAR(20),                       -- 电话
  test_date DATE NOT NULL,                 -- 检测日期
  test_time TIME,                          -- 检测时间
  result VARCHAR(20) NOT NULL,             -- 结果：阴性、阳性、待检
  test_location VARCHAR(255),              -- 检测地点
  sample_type VARCHAR(50),                 -- 样本类型：咽拭子、鼻拭子等
  remarks TEXT,                            -- 备注
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 添加索引以提高查询性能
CREATE INDEX idx_id_number ON nucleic_acid_results(id_number);
CREATE INDEX idx_test_date ON nucleic_acid_results(test_date);
CREATE INDEX idx_result ON nucleic_acid_results(result);

-- 启用 RLS (行级安全)
ALTER TABLE nucleic_acid_results ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略 (允许所有操作，因为不需要登录)
CREATE POLICY "Allow all operations" ON nucleic_acid_results
  FOR ALL
  USING (true)
  WITH CHECK (true);
